### ISSUE TITLE
some question about getTransformStamped function

### ISSUE THREAD

**Issue by ZRazer** [tigerk0430/V-Rep-Autonomous-Vehicle-Simulator#2]
I looked at the definition of the frame “**map**” in the lua script. Can I think that the “**map**” can also be considered as the “**odom**” of the vehicle? At the vehicle lua script , "**map**" was defined its tf frame with “-1”，is this means the "**map**" set in the vehicle's original position?
Looking forward to your reply.

**Comment by gyubeomim** [comment]
In the script of vehicle object

getTransformStamped() function looks like this

```
transformations[1]=(getTransformStamped(h_vehicle,'base_link',-1,'map'))

...

function getTransformStamped(objHandle, name, relTo, relToName)
    t=simROS.getTime(1)
    p=sim.getObjectPosition(objHandle,relTo)
    o=sim.getObjectQuaternion(objHandle,relTo)

    -- sim.auxiliaryConsolePrint(aux_console, vrep_clock.."\n")

    return {
        header={
            stamp=t,
            frame_id=relToName
        },
        child_frame_id=name,
        transform={
            -- ROS has definition x=front y=side z=up
            translation={x=p[1],y=p[2],z=p[3]},--V-rep
            rotation={x=o[1],y=o[2],z=o[3],w=o[4]}--v-rep
        }
    }
end
```

and `-1` goes to `sim.getObjectPosition(objHandle, -1)`
and the meaning of getObjectPosition(..., -1) is an **absolute position** of that object as well as Quaternion
see more at http://www.coppeliarobotics.com/helpFiles/en/regularApi/simGetObjectPosition.htm

because there is no published odometry from V-Rep simulator, You can think "**map**" as a "**odom**"

hope it helps :-)

**Comment by gyubeomim** [comment]
close issue due to inactivity
